version: "3"
services:
  kong:
    image: kong:1.2.0
    volumes:
      - "${PWD}/kong-config.yml:/config/kong-config.yml"
    command: [ "kong", "start" ]
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/config/kong-config.yml
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
    - default

  buggy-service:
    build: ./buggy-service
    ports:
    - "8010:8000"
    - "8011:8001"
    - "8012:8002"
    networks:
    - default

  udp-log:
    build: ./udp-log
    ports:
    - "8020:8000"
    networks:
    - default

networks:
  default:
